name: My First Pipeline

on:
  push:        # run when you push code
    branches: [ Feature/migration ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get my repo
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Pipeline is running!"
